### PR TITLE
B2g gingerbread

### PR DESCRIPTION
**Pull request by michaelwu**
This makes /system/b2g/b2g executable. (0755)

### CODE REVIEW

**Comment by joneschrisg** [comment]
Does b2g really need to be root?  Can it be system instead?

**Comment by michaelwu** [comment]
How does that matter? b2g isn't suid

**Comment by joneschrisg** [comment]
Are we dropping root permissions after execing?  b2g doesn't really want to be able to load kernel modules, e.g.  It's running arbitrary web content for the near future.

**Comment by michaelwu** [comment]
Nope there's no permission dropping at the moment. Also, that wouldn't change this pull request.

**Pull request merged**
